#!/bin/sh

lb config noauto \
    --distribution kali-rolling \
    --archive-areas "main contrib non-free non-free-firmware" \
    --mirror-bootstrap "http://http.kali.org/kali" \
    --mirror-chroot "http://http.kali.org/kali" \
    --mirror-chroot-security "http://http.kali.org/kali" \
    --mirror-binary "http://http.kali.org/kali" \
    --mirror-binary-security "http://http.kali.org/kali" \
    --mirror-debian-installer "http://http.kali.org/kali" \
    --parent-mirror-bootstrap "http://http.kali.org/kali" \
    --parent-mirror-chroot "http://http.kali.org/kali" \
    --parent-mirror-chroot-security "http://http.kali.org/kali" \
    --parent-mirror-binary "http://http.kali.org/kali" \
    --parent-mirror-binary-security "http://http.kali.org/kali" \
    --parent-mirror-debian-installer "http://http.kali.org/kali" \
    --keyring-packages kali-archive-keyring \
    --debian-installer live \
    --debian-installer-gui true \
    --debootstrap-options "--include=apt-transport-https,ca-certificates,kali-archive-keyring --keyring=/usr/share/keyrings/kali-archive-keyring.gpg" \
    --iso-application "Kali Custom i3 Gruvbox" \
    --iso-volume "KALI-CUSTOM" \
    --linux-flavours amd64 \
    --security false \
    --updates false \
    --apt-indices false \
    "${@}"
